GET https://script.google.com/macros/s/AKfycbxRMaVtB_k9BViFkvwDeeddvSe3-sIOLG4E2AR4VFD1sdFwFdS4r2qjySKqKN4YNWAfMw/exec?action=Create&token_acess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c&nomecliente=Bianca&data=29/05/2024&valor=250&horarioinicial=11-00&horariofinal=15-00&descricao=Progressiva&pagamento=Dinheiro&id=10